sudo: required
language: node_js
dist: trusty

node_js:
  - "8.9"

before_script:
  - yarn

script:
  - gulp

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
